includes:
  - ../module_base.yaml

profiling:
  enable_profiling: true
  save_traces_folder: "profile_trace"
  profile_freq: 100

metrics:
  log_freq: 10
  enable_tensorboard: true
  save_tb_folder: "tb"

optimizer:
  name: "AdamW"
  lr: 3e-4
  eps: 1e-8

lr_scheduler:
  # lr scheduler warm up
  warmup_steps: 200

training:
  batch_size: 1
  seq_len: 8192
  max_norm: 1.0
  steps: 1000
  compile: false
  dataset: "c4"

parallelism:
  data_parallel_replicate_degree: 1
  data_parallel_shard_degree: -1
  tensor_parallel_degree: 1
  pipeline_parallel_degree: 1
  context_parallel_degree: 1
  enable_async_tensor_parallel: false

checkpoint:
  enable_checkpoint: false
  folder: "checkpoint"
  interval: 500
  model_weights_only: false
  export_dtype: "float32"
  async_mode: "disabled" # ["disabled", "async", "async_with_pinned_mem"]

activation_checkpoint:
  mode: "selective" # ["none", "selective", "full"]
  selective_ac_option: "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

float8:
  enable_fsdp_float8_all_gather: false
  precompute_float8_dynamic_scale_for_fsdp: false
  filter_fqns: ["output"]

experimental:
  custom_args_module : "primus.backends.torchtitan.primus_turbo_extensions.config_extension"

primus_turbo:
  enable_primus_turbo : true
  enable_attention_float8 : false
